# syntax=docker/dockerfile:1.4
FROM python:3.8-alpine

RUN apk add --no-cache make
RUN adduser -D testuser

WORKDIR /app

# COPY and install the requirements
COPY requirements/test.txt requirements/test.txt

RUN <<-EOF
    python -m venv .venv
    .venv/bin/pip3 install -r requirements/test.txt
EOF

COPY Makefile .
COPY .pylintrc .
COPY pytest.ini .

COPY docker/test-entrypoint.sh /app/test-entrypoint.sh


RUN <<-EOF
    chmod +x /app/test-entrypoint.sh
    chown -R testuser:testuser /app
EOF

USER testuser

ENTRYPOINT ["./test-entrypoint.sh"]