FROM python:3.9-slim

WORKDIR /app

# Install dependencies FIXED VERSION
RUN apt-get update && apt-get install --no-install-recommends -y \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install
COPY requirements/prod.txt .
RUN pip install --no-cache-dir -r prod.txt

# Copy application
COPY app/ ./app/
COPY migrations/ ./migrations/

# Environment variables
ENV FLASK_APP=app
ENV FLASK_ENV=production

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]
